### ISSUE TITLE
PaddleDetection怎么在test测试集（COCO格式标注）上计算map呀？

### ISSUE THREAD

**Issue by atomrun39** [PaddlePaddle/PaddleDetection#1267]
例如ppyolo模型，使用训练保存的checkpoint评估模型，如下命令，但这不是只评估了验证集val上的检测指标吗？
CUDA_VISIBLE_DEVICES=0 python tools/eval.py -c configs/ppyolo/ppyolo.yml -o weights=output/ppyolo/best_model

**Comment by qingqing01** [comment]
@atomrun39 @shuxsu 

Paddle大部分模型的指标都是验证集(val集)评估，val集下载到的数据里已提供了标注，使用tools/eval.py即可。  无需到COCO官网提交。  PPYOLO为了和YOLOv4做比较，即评估了val集，也评估了test集。

自己的项目，一般评估val集即可。

**Comment by atomrun39** [comment]
> @atomrun39 @shuxsu
> 
> Paddle大部分模型的指标都是验证集(val集)评估，val集下载到的数据里已提供了标注，使用tools/eval.py即可。 无需到COCO官网提交。 PPYOLO为了和YOLOv4做比较，即评估了val集，也评估了test集。
> 
> 自己的项目，一般评估val集即可。

了解，谢谢了

**Comment by xinxin108** [comment]
> > 例如ppyolo模型，使用训练保存的检查点

> > 例如ppyolo模型，使用训练保存的检查点评估模型，如下命令，而不是只评估了验证集val上的检测指标吗？
> > CUDA_VISIBLE_DEVICES = 0 python tools / eval.py -c configs / ppyolo / ppyolo.yml -o权重=输出/ Pyyolo /最佳模型
> 
> 我之前都是把4个IOU不同的值直接把ap / ar加起来平均

您是怎么求得AP值的呢？

**Comment by SixGodGG** [comment]
@qingqing01  你好 我运行eval后，并没有直接得到mAP，paddledetection中怎么直接得到mAP？ 
![QQ截图20201221132054](https://user-images.githubusercontent.com/6395366/102742308-85da6980-438f-11eb-8d8a-ad3944cb0987.jpg)

**Comment by xinxin108** [comment]
请问您是？



---原始邮件---
发件人: "Night"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 中午1:22
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"xinxin108"<1306014217@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] PaddleDetection怎么在test测试集（COCO格式标注）上计算map呀？ (#1267)




 
@qingqing01  你好 我运行eval后，并没有直接得到mAP，paddledetection中怎么直接得到mAP？

**Comment by SixGodGG** [comment]
@xinxin108  什么意思 ？我是用户。我自己在aistudio上训练了ppyolo， 有eval 数据集和json标注文件，也用咱们的eval生成了bbox.json 文件，但是现在 eval出来的都是AP  AP，请问我怎么用这些AP  AR计算 mAP

**Comment by xinxin108** [comment]
哦哦哦 您是群发的吧 我也是用户 不好意思 我以为您是给我发的



---原始邮件---
发件人: "Night"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 中午1:28
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"xinxin108"<1306014217@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] PaddleDetection怎么在test测试集（COCO格式标注）上计算map呀？ (#1267)




 
@xinxin108  什么意思 ？我是用户。我自己在aistudio上训练了ppyolo， 有eval 数据集和json标注文件，也用咱们的eval生成了bbox.json 文件，但是现在 eval出来的都是AP  AP，请问我怎么用这些AP  AR计算 mAP

**Comment by xinxin108** [comment]
不知道为啥我会收到邮件，但是我刚好知道这个问题，您直接对所有类别的ap值求和再除以类别数，就得到map啦



---原始邮件---
发件人: "Night"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 中午1:28
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"xinxin108"<1306014217@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] PaddleDetection怎么在test测试集（COCO格式标注）上计算map呀？ (#1267)




 
@xinxin108  什么意思 ？我是用户。我自己在aistudio上训练了ppyolo， 有eval 数据集和json标注文件，也用咱们的eval生成了bbox.json 文件，但是现在 eval出来的都是AP  AP，请问我怎么用这些AP  AR计算 mAP

**Comment by SixGodGG** [comment]
> 不知道为啥我会收到邮件，但是我刚好知道这个问题，您直接对所有类别的ap值求和再除以类别数，就得到map啦
> […](#)
> ---原始邮件--- 发件人: "Night"<notifications@github.com&gt; 发送时间: 2020年12月21日(周一) 中午1:28 收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"xinxin108"<1306014217@qq.com&gt;; 主题: Re: [PaddlePaddle/PaddleDetection] PaddleDetection怎么在test测试集（COCO格式标注）上计算map呀？ (#1267) @xinxin108 什么意思 ？我是用户。我自己在aistudio上训练了ppyolo， 有eval 数据集和json标注文件，也用咱们的eval生成了bbox.json 文件，但是现在 eval出来的都是AP AP，请问我怎么用这些AP AR计算 mAP — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

我主要是不知道怎么用以上eval的数据计算AP，你能详细说一下嘛？

**Comment by xinxin108** [comment]
我也不太清楚，我没有用coco数据集，要不你加上我qq，截图我看看，也不一定能帮上你



---原始邮件---
发件人: "Night"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 中午1:40
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"xinxin108"<1306014217@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] PaddleDetection怎么在test测试集（COCO格式标注）上计算map呀？ (#1267)




  
不知道为啥我会收到邮件，但是我刚好知道这个问题，您直接对所有类别的ap值求和再除以类别数，就得到map啦
 …
 ---原始邮件--- 发件人: "Night"<notifications@github.com&gt; 发送时间: 2020年12月21日(周一) 中午1:28 收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"xinxin108"<1306014217@qq.com&gt;; 主题: Re: [PaddlePaddle/PaddleDetection] PaddleDetection怎么在test测试集（COCO格式标注）上计算map呀？ (#1267) @xinxin108 什么意思 ？我是用户。我自己在aistudio上训练了ppyolo， 有eval 数据集和json标注文件，也用咱们的eval生成了bbox.json 文件，但是现在 eval出来的都是AP AP，请问我怎么用这些AP AR计算 mAP — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我主要是不知道怎么用以上eval的数据计算AP，你能详细说一下嘛？
