### ISSUE TITLE
Is it possible to export a trained PPYolo model to ONNX?

### ISSUE THREAD

**Issue by LukeAI** [PaddlePaddle/PaddleDetection#1400]
Is it possible to export a trained PPYolo model to ONNX or some other format that could be used for inference without PaddleDetection?

**Comment by qingqing01** [comment]
paddle2onnx in X2Paddle https://github.com/PaddlePaddle/X2Paddle/#paddle2onnx supports to convert YOLOv3 model of PaddlePaddle to ONNX,  (need to set --opset 11) . But not support PP-YOLO now, since the lack of supporting for `deformable_conv` and `matrix_nms` (of course, the post preprocess matrix_nms or nms can be implented by users)
