### ISSUE TITLE
加载自己的pretrain_weights错误！！

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#1903]
cascade_rcnn_dcn_r101_vd_fpn_3x_server_side.yml 中加载自己的预训练模型：
如：#pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet101_vd_ssld_pretrained.tar
#pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/cascade_rcnn_dcn_r101_vd_fpn_3x_server_side.pdparams
pretrain_weights: G:/paddle/PaddleDetection0.5/cascade_rcnn_dcn_r101_vd_fpn_tiles.pdparams
finetune_exclude_pretrained_params: ['cls_score', 'bbox_pred']
训练时报错：：
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
W1215 23:54:17.928540  3088 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.2
W1215 23:54:17.935541  3088 device_context.cc:346] device: 0, cuDNN Version: 7.6.
2020-12-15 23:54:20,999-WARNING: variable bbox_pred_3_b not used
2020-12-15 23:54:20,999-WARNING: variable cls_score_3_w not used
2020-12-15 23:54:20,999-WARNING: variable cls_score_b not used
2020-12-15 23:54:20,999-WARNING: variable cls_score_2_w not used
2020-12-15 23:54:21,000-WARNING: variable bbox_pred_b not used
2020-12-15 23:54:21,000-WARNING: variable bbox_pred_3_w not used
2020-12-15 23:54:21,000-WARNING: variable bbox_pred_2_b not used
2020-12-15 23:54:21,000-WARNING: variable cls_score_3_b not used
2020-12-15 23:54:21,000-WARNING: variable cls_score_2_b not used
2020-12-15 23:54:21,000-WARNING: variable bbox_pred_2_w not used
2020-12-15 23:54:21,001-WARNING: variable cls_score_w not used
2020-12-15 23:54:21,001-WARNING: variable bbox_pred_w not used
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
W1215 23:54:21.547539  3088 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
G:\paddle\PaddleDetection0.5\ppdet\data\reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1456: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  if 'prob' in inspect.getargspec(func)[0]:
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1463: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  assert 'replace' == inspect.getargspec(func)[0][-1]
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1461: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  if 'replace' in inspect.getargspec(func)[0]:
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1468: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  if 'bboxes' not in inspect.getargspec(func)[0]:
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1476: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  assert 'bboxes' == inspect.getargspec(func)[0][1]
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1480: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  if 'prob' in inspect.getargspec(func)[0]:
tools/train.py:261: RuntimeWarning: divide by zero encountered in double_scalars
  ips = float(cfg['TrainReader']['batch_size']) / time_cost
2020-12-15 23:54:23,973-INFO: iter: 0, lr: 0.000250, 'loss_cls_0': '2.055031', 'loss_loc_0': '0.129237', 'loss_cls_1': '1.033265', 'loss_loc_1': '0.040041', 'loss_cls_2': '0.541540', 'loss_loc_2': '0.007862', 'loss_rpn_cls': '0.011049'
, 'loss_rpn_bbox': '0.203873', 'loss': '4.021898', eta: 0:00:00, batch_cost: 0.00000 sec, ips: inf images/sec
Traceback (most recent call last):
  File "tools/train.py", line 377, in <module>
    main()
  File "tools/train.py", line 248, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 1107, in run
    six.reraise(*sys.exc_info())
  File "D:\anaconda\envs\paddle_env\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\anaconda\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 1105, in run
    return_merged=return_merged)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 1242, in _run_impl
    return_merged=return_merged)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\paddle\fluid\executor.py", line 910, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official soluti
on about CUDA Error.] (at D:\2.0.0-rc0\paddle\paddle\fluid\platform\stream\cuda_stream.cc:65)
求大神指导！！！！

**Comment by tianlanshidai** [comment]
可能是和背景类有关？

**Comment by wangkan83** [comment]
@tianlanshidai ，加载的预训练模型参数是上一次训练后保存的，数据集标签一样的，只是扩增了数据集。求大神指点！！

**Comment by willthefrog** [comment]
weight应该是正常加载了，已经跑了一个step了，你是多卡跑的eval吗？试试单卡跑呢

**Comment by wangkan83** [comment]
@willthefrog , train和eval都是单卡。

**Comment by willthefrog** [comment]
train和eval是同一个环境吗？

**Comment by wangkan83** [comment]
@willthefrog ,是同一环境，train.py --eval后就输出了iter0，然后就终止了：

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
W1218 10:43:45.178596  8288 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.2
W1218 10:43:45.190598  8288 device_context.cc:346] device: 0, cuDNN Version: 7.6.
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
W1218 10:43:51.071151  8288 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
G:\paddle\PaddleDetection0.5\ppdet\data\reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1456: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  if 'prob' in inspect.getargspec(func)[0]:
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1461: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  if 'replace' in inspect.getargspec(func)[0]:
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1463: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  assert 'replace' == inspect.getargspec(func)[0][-1]
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1468: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  if 'bboxes' not in inspect.getargspec(func)[0]:
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1476: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  assert 'bboxes' == inspect.getargspec(func)[0][1]
G:\paddle\PaddleDetection0.5\ppdet\data\transform\autoaugment_utils.py:1480: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  if 'prob' in inspect.getargspec(func)[0]:
tools/train.py:261: RuntimeWarning: divide by zero encountered in double_scalars
  ips = float(cfg['TrainReader']['batch_size']) / time_cost
2020-12-18 10:43:53,543-INFO: iter: 0, lr: 0.000250, 'loss_cls_0': '0.036453', 'loss_loc_0': '0.023888', 'loss_cls_1': '0.017579', 'loss_loc_1': '0.054506', 'loss_cls_2': '0.005596', 'loss_loc_2': '0.036121', 'loss_rpn_cls': '0.009210'
, 'loss_rpn_bbox': '0.210526', 'loss': '0.393879', eta: 0:00:00, batch_cost: 0.00000 sec, ips: inf images/sec

(paddle_env) G:\paddle\PaddleDetection0.5>
