### ISSUE TITLE
Flip of original image `image_flip` not used in mstest

### ISSUE THREAD

**Issue by sbl1996** [PaddlePaddle/PaddleDetection#384]
Using 2 scales with their flips, I tried to put `fluid.layers.Print` in `build_multi_scale` of `CascadeRCNNClsAware` (line 184), and found that only `image`, `image_scale_0 ` and `image_flip_scale_0 ` are printed, but not `image_flip`. If this behavior is expected, could you tell me where is `image_flip` used? The related config is pasted below.

EvalReader:
 inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
    multi_scale: true
    num_scales: 4
    use_flip: true
 dataset:
    !COCODataSet
    image_dir: images
    anno_path: train_val.json
    dataset_dir: /home/hrvvi/29831
 sample_transforms:
 - !DecodeImage
    to_rgb: true
 - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
 - !MultiscaleTestResize
    origin_target_size: 1440
    origin_max_size: 2560
    target_size: [960]
    max_size: 2560
    use_flip: true
 - !Permute
    channel_first: true
    to_bgr: false
 batch_transforms:
 - !PadMultiScaleTest
    pad_to_stride: 32
 batch_size: 1
 shuffle: false
 drop_empty: false
 worker_num: -1
 use_process: false

**Comment by qingqing01** [comment]
@sbl1996 

In tools/eval.py:

Pass `inputs_def` to `build_inputs` in CascadeRCNNClsAware:  

https://github.com/PaddlePaddle/PaddleDetection/blob/366eb59c9ff75d8cab093f0449ead860e0b75649/tools/eval.py#L79-L80

then, get image,  multi-scale images and their flipped images.

https://github.com/PaddlePaddle/PaddleDetection/blob/366eb59c9ff75d8cab093f0449ead860e0b75649/ppdet/modeling/architectures/cascade_rcnn_cls_aware.py#L290-L295

when,  predict for each image:

https://github.com/PaddlePaddle/PaddleDetection/blob/366eb59c9ff75d8cab093f0449ead860e0b75649/ppdet/modeling/architectures/cascade_rcnn_cls_aware.py#L181-L183

`self.im_info_names` includes the `image_flip`.

In order to do posting pre-process, marked flipped images in the output results:

https://github.com/PaddlePaddle/PaddleDetection/blob/366eb59c9ff75d8cab093f0449ead860e0b75649/ppdet/modeling/architectures/cascade_rcnn_cls_aware.py#L251-L257

**Comment by sbl1996** [comment]
After inserting `print(self.im_info_names)` into line 180,
https://github.com/PaddlePaddle/PaddleDetection/blob/366eb59c9ff75d8cab093f0449ead860e0b75649/ppdet/modeling/architectures/cascade_rcnn_cls_aware.py#L177-L183
the output is:
`['image', 'im_info', 'image_scale_0', 'im_info_image_scale_0', 'image_flip_scale_0', 'im_info_image_flip_scale_0']`.
`image_flip ` is not in it.

**Comment by littletomatodonkey** [comment]
Thanks for your feedback, we fix the problem, you can refer to #385 , now it works.
![image](https://user-images.githubusercontent.com/14270174/77332195-b20f7e00-6d5c-11ea-9641-4ec9ef4b2300.png)
