### ISSUE TITLE
[Other General Issues]yolov3训练参数问题

### ISSUE THREAD

**Issue by Viperwd** [PaddlePaddle/PaddleDetection#4366]
请问我将backbone替换为resnet50vd_dcn，目前设置为base_lr: 0.001，batch_size: 16，训练集是6361张图片，已经跑了270轮，和用yolov3预训练40之后的精度差不多，想再提高准确率是不是很难了？还是说继续训练下去会有更好的结果？之前尝试不少参数，但是最后精度也是差不多，总感觉是训练参数的问题，我应该做出什么样的调整呢？

**Comment by ghostxsl** [comment]
看目前的情况的话，我感觉你这个再训下去可能也不会有更好的结果了。你也可以尝试用一下ppyolo看看效果如何呢

**Comment by Viperwd** [comment]
> 看目前的情况的话，我感觉你这个再训下去可能也不会有更好的结果了。你也可以尝试用一下ppyolo看看效果如何呢

请问那么应该使用哪个训练参数文件呢？我看有1x,2x,365e等，学习率应该是多少呢？

**Comment by ghostxsl** [comment]
如果要使用ppyolo的话，建议使用365e，因为ppyolo的收敛时间会比较长

**Comment by zmdcs** [comment]
请问一下你使用的AIStudio平台还是自己的电脑做实验呢？

**Comment by ghostxsl** [comment]
我是用服务器跑的实验，没有用过AIStudio

**Comment by zmdcs** [comment]
服务器是？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 下午4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Other General Issues]yolov3训练参数问题 (Issue #4366)





 
我是用服务器跑的实验，没有用过AIStudio
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghostxsl** [comment]
就是自己的主机跑的实验

**Comment by zmdcs** [comment]
windows系统吗？方便的话能不能加个联系方式，我感觉AIStudio跑的太慢了，可是Windows我不会部署PaddleDetection





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Other General Issues]yolov3训练参数问题 (Issue #4366)





 
就是自己的主机跑的实验
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghostxsl** [comment]
我是用的linux，不过windows应该是一样的，而且你只是跑训练的话也不需要部署PaddleDetection吧。
有事的话你可以发邮件给我，xushangliang@baidu.com是我邮箱～

**Comment by zmdcs** [comment]
我用的是PaddleDetection底下的train、eval、infer这些工具类，一直就在用他们的配置文件训练，这些难道不用配置Paddledetection就能用吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Other General Issues]yolov3训练参数问题 (Issue #4366)





 
我是用的linux，不过windows应该是一样的，而且你只是跑训练的话也不需要部署PaddleDetection吧。
 ***@***.***是我邮箱～
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghostxsl** [comment]
需要的，基本的环境配置还是要搭建的。

**Comment by zmdcs** [comment]
可以加个微信吗13787146430





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Other General Issues]yolov3训练参数问题 (Issue #4366)





 
需要的，基本的环境配置还是要搭建的。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
