### ISSUE TITLE
AP、AR是如何打印出来的？

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleDetection#4657]
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.123
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.401
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.039
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.104
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.041
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.098
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.159
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.324
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.454
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.217
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.453
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.553

**Comment by nemonameless** [comment]
cocoapi 里的函数打印的

**Comment by zmdcs** [comment]
paddleDetection里有cocoapi这个文件夹吗?请问在哪里





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月23日(星期二) 中午1:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] AP、AR是如何打印出来的？ (Issue #4657)





 
cocoapi 里的函数打印的
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gaorui999** [comment]
有没有代码命令展示，我还是有些不明白？

**Comment by nemonameless** [comment]
首先pip安装pycocotools包
代码里会有
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
ppdet里的打印调用在此：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/metrics/coco_utils.py#L114
cocoapi里的原始代码在此
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L422

主要代码：
```
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

coco_gt = COCO(anno_file) # anno_file是gt json的路径
coco_dt = coco_gt.loadRes(jsonfile) # jsonfile是结果json的路径
coco_eval = COCOeval(coco_gt, coco_dt, 'bbox')  # 'bbox'评估检测，还有‘segm’是评估实例分割的，‘keypoints’是评估关键点检测

coco_eval.evaluate()
coco_eval.accumulate()
coco_eval.summarize() # 打印指标
```

**Comment by gaorui999** [comment]
@nemonameless  非常感谢您的回复，解决了我的问题。我还有一个疑惑，如果是VOC数据集的是不是就没有办法打印这个评估？

**Comment by nemonameless** [comment]
voc格式，没法用COCO类加载gt 结果文件，就无法调用cocoapi计算评估。可以将gt 和结果文件都转为coco格式，所以建议直接一开始就把自己的数据集转为coco格式去使用。

**Comment by gaorui999** [comment]
@nemonameless  感谢您的回复，完美的解决了我的疑惑！
