### ISSUE TITLE
rbox_iou 编译外部算子报错

### ISSUE THREAD

**Issue by sherwin-silin-chen** [PaddlePaddle/PaddleDetection#7164]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

GCC 版本 5.4.0
在编译外部算子的时候报错：
running install
/home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
creating ext_op.egg-info
writing ext_op.egg-info/PKG-INFO
writing dependency_links to ext_op.egg-info/dependency_links.txt
writing top-level names to ext_op.egg-info/top_level.txt
writing manifest file 'ext_op.egg-info/SOURCES.txt'
reading manifest file 'ext_op.egg-info/SOURCES.txt'
writing manifest file 'ext_op.egg-info/SOURCES.txt'
installing library code to build/ext_op/bdist.linux-x86_64/egg
running install_lib
running build_ext
Compiling user custom op, it will cost a few seconds.....
building 'ext_op' extension
gcc -pthread -B /home/chensilin/anaconda3/envs/paddledet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/include -I/home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/include/third_party -I/home/wangqingzhong/tools/cuda-10.2/include -I/home/chensilin/anaconda3/envs/paddledet/include/python3.7m -c /home/chensilin/PaddleDetection/ppdet/ext_op/csrc/rbox_iou/matched_rbox_iou_op.cc -o /home/chensilin/PaddleDetection/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-37/matched_rbox_iou_op.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/wangqingzhong/tools/cuda-10.2/bin/nvcc -I/home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/include -I/home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/include/third_party -I/home/wangqingzhong/tools/cuda-10.2/include -I/home/chensilin/anaconda3/envs/paddledet/include/python3.7m -c /home/chensilin/PaddleDetection/ppdet/ext_op/csrc/rbox_iou/matched_rbox_iou_op.cu -o /home/chensilin/PaddleDetection/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-37/matched_rbox_iou_op.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
In file included from /home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/include/paddle/extension.h:18:0,
                 from /home/chensilin/PaddleDetection/ppdet/ext_op/csrc/rbox_iou/matched_rbox_iou_op.cu:18:
/home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/include/paddle/phi/api/all.h:18:2: error: #error C++14 or later compatible compiler is required to use Paddle.
 #error C++14 or later compatible compiler is required to use Paddle.
  ^
In file included from /usr/include/c++/4.8.2/tuple:35:0,
                 from /home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/include/paddle/phi/api/include/api.h:3,
                 from /home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/include/paddle/phi/api/all.h:28,
                 from /home/chensilin/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/include/paddle/extension.h:18,
                 from /home/chensilin/PaddleDetection/ppdet/ext_op/csrc/rbox_iou/matched_rbox_iou_op.cu:18:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
error: command '/home/wangqingzhong/tools/cuda-10.2/bin/nvcc' failed with exit code 1

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/ext_op/README.md
请换用 gcc 8.2 试试

**Comment by sherwin-silin-chen** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/ext_op/README.md
> 请换用 gcc 8.2 试试

更换到 8.2后 一样会出现相同的错误

**Comment by sherwin-silin-chen** [comment]
我的系统版本为CentOS Linux release 7.5.1804 (Core)
GCC版本 8.2
PaddlePadlle版本2.2
python 3.7

**Comment by chl916185** [comment]
python setup.py install
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
running install
/opt/conda/envs/paddledet/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/conda/envs/paddledet/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating ext_op.egg-info
writing ext_op.egg-info/PKG-INFO
writing dependency_links to ext_op.egg-info/dependency_links.txt
writing top-level names to ext_op.egg-info/top_level.txt
writing manifest file 'ext_op.egg-info/SOURCES.txt'
reading manifest file 'ext_op.egg-info/SOURCES.txt'
writing manifest file 'ext_op.egg-info/SOURCES.txt'
installing library code to build/ext_op/bdist.linux-x86_64/egg
running install_lib
running build_ext
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  return (isinstance(seq, collections.Sequence) and
Compiling user custom op, it will cost a few seconds.....
building 'ext_op' extension
gcc -pthread -B /opt/conda/envs/paddledet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include -I/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.0/include -I/opt/conda/envs/paddledet/include/python3.8 -c /home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc -o /home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.o -DPADDLE_WITH_CUDA -w -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_dtype.h:20,
                 from /opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_dispatch.h:17,
                 from /opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_all.h:27,
                 from /opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension.h:18,
                 from /home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:19:
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc: In function ‘std::vector<paddle::Tensor> MatchedRboxIouCPUForward(const Tensor&, const Tensor&)’:
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:33:14: error: ‘const Tensor’ {aka ‘const class paddle::Tensor’} has no member named ‘is_cpu’
   PD_CHECK(x.is_cpu(), #x " must be a CPU Tensor.")
              ^~~~~~
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_exception.h:25:63: note: in definition of macro ‘PD_UNLIKELY’
 #define PD_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
                                                               ^~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:33:3: note: in expansion of macro ‘PD_CHECK’
   PD_CHECK(x.is_cpu(), #x " must be a CPU Tensor.")
   ^~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:38:3: note: in expansion of macro ‘CHECK_INPUT_CPU’
   CHECK_INPUT_CPU(rbox1);
   ^~~~~~~~~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:33:14: error: ‘const Tensor’ {aka ‘const class paddle::Tensor’} has no member named ‘is_cpu’
   PD_CHECK(x.is_cpu(), #x " must be a CPU Tensor.")
              ^~~~~~
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_exception.h:25:63: note: in definition of macro ‘PD_UNLIKELY’
 #define PD_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
                                                               ^~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:33:3: note: in expansion of macro ‘PD_CHECK’
   PD_CHECK(x.is_cpu(), #x " must be a CPU Tensor.")
   ^~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:39:3: note: in expansion of macro ‘CHECK_INPUT_CPU’
   CHECK_INPUT_CPU(rbox2);
   ^~~~~~~~~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:43:25: error: ‘empty’ is not a member of ‘paddle’
   auto output = paddle::empty({rbox_num}, rbox1.dtype(), paddle::CPUPlace());
                         ^~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:43:49: error: ‘const Tensor’ {aka ‘const class paddle::Tensor’} has no member named ‘dtype’; did you mean ‘type’?
   auto output = paddle::empty({rbox_num}, rbox1.dtype(), paddle::CPUPlace());
                                                 ^~~~~
                                                 type
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:43:66: error: ‘CPUPlace’ is not a member of ‘paddle’
   auto output = paddle::empty({rbox_num}, rbox1.dtype(), paddle::CPUPlace());
                                                                  ^~~~~~~~
In file included from /opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_all.h:27,
                 from /opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension.h:18,
                 from /home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:19:
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc: In lambda function:
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:48:76: error: expected primary-expression before ‘>’ token
                                    rbox2.data<data_t>(), output.data<data_t>());
                                                                            ^
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_dispatch.h:27:5: note: in definition of macro ‘PD_PRIVATE_CASE_TYPE_USING_HINT’
     __VA_ARGS__();                                                        \
     ^~~~~~~~~~~
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_dispatch.h:40:7: note: in expansion of macro ‘PD_PRIVATE_CASE_TYPE’
       PD_PRIVATE_CASE_TYPE(NAME, ::paddle::DataType::FLOAT32, float,      \
       ^~~~~~~~~~~~~~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:45:3: note: in expansion of macro ‘PD_DISPATCH_FLOATING_TYPES’
   PD_DISPATCH_FLOATING_TYPES(rbox1.type(), "matched_rbox_iou_cpu_kernel", ([&] {
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:48:78: error: expected primary-expression before ‘)’ token
                                    rbox2.data<data_t>(), output.data<data_t>());
                                                                              ^
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_dispatch.h:27:5: note: in definition of macro ‘PD_PRIVATE_CASE_TYPE_USING_HINT’
     __VA_ARGS__();                                                        \
     ^~~~~~~~~~~
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_dispatch.h:40:7: note: in expansion of macro ‘PD_PRIVATE_CASE_TYPE’
       PD_PRIVATE_CASE_TYPE(NAME, ::paddle::DataType::FLOAT32, float,      \
       ^~~~~~~~~~~~~~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:45:3: note: in expansion of macro ‘PD_DISPATCH_FLOATING_TYPES’
   PD_DISPATCH_FLOATING_TYPES(rbox1.type(), "matched_rbox_iou_cpu_kernel", ([&] {
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc: In lambda function:
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:48:76: error: expected primary-expression before ‘>’ token
                                    rbox2.data<data_t>(), output.data<data_t>());
                                                                            ^
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_dispatch.h:27:5: note: in definition of macro ‘PD_PRIVATE_CASE_TYPE_USING_HINT’
     __VA_ARGS__();                                                        \
     ^~~~~~~~~~~
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_dispatch.h:42:7: note: in expansion of macro ‘PD_PRIVATE_CASE_TYPE’
       PD_PRIVATE_CASE_TYPE(NAME, ::paddle::DataType::FLOAT64, double,     \
       ^~~~~~~~~~~~~~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:45:3: note: in expansion of macro ‘PD_DISPATCH_FLOATING_TYPES’
   PD_DISPATCH_FLOATING_TYPES(rbox1.type(), "matched_rbox_iou_cpu_kernel", ([&] {
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:48:78: error: expected primary-expression before ‘)’ token
                                    rbox2.data<data_t>(), output.data<data_t>());
                                                                              ^
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_dispatch.h:27:5: note: in definition of macro ‘PD_PRIVATE_CASE_TYPE_USING_HINT’
     __VA_ARGS__();                                                        \
     ^~~~~~~~~~~
/opt/conda/envs/paddledet/lib/python3.8/site-packages/paddle/include/paddle/extension/include/ext_dispatch.h:42:7: note: in expansion of macro ‘PD_PRIVATE_CASE_TYPE’
       PD_PRIVATE_CASE_TYPE(NAME, ::paddle::DataType::FLOAT64, double,     \
       ^~~~~~~~~~~~~~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:45:3: note: in expansion of macro ‘PD_DISPATCH_FLOATING_TYPES’
   PD_DISPATCH_FLOATING_TYPES(rbox1.type(), "matched_rbox_iou_cpu_kernel", ([&] {
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc: In function ‘std::vector<paddle::Tensor> MatchedRboxIouCPUForward(const Tensor&, const Tensor&)’:
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:51:17: error: could not convert ‘{output}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<paddle::Tensor>’
   return {output};
                 ^
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc: In function ‘std::vector<paddle::Tensor> MatchedRboxIouForward(const Tensor&, const Tensor&)’:
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:66:13: error: ‘const Tensor’ {aka ‘const class paddle::Tensor’} has no member named ‘is_cpu’
   if (rbox1.is_cpu()) {
             ^~~~~~
/home/chenhonglei/works/PaddleDetection_develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc:69:20: error: ‘const Tensor’ {aka ‘const class paddle::Tensor’} has no member named ‘is_gpu’
   } else if (rbox1.is_gpu()) {
                    ^~~~~~
error: command '/usr/bin/gcc' failed with exit code 1
@nemonameless 更换为8.2依然报错

**Comment by chl916185** [comment]
> Author
解决了吗

**Comment by wangxinxin08** [comment]
@chl916185 这个是Paddle版本不对，应该安装2.4的Paddle版本，和上面的问题不是一个问题

**Comment by yuxin7** [comment]
> 我的系统版本为CentOS Linux release 7.5.1804 (Core) GCC版本 8.2 PaddlePadlle版本2.2 python 3.7
我也是Centos7.6,cuda11.3, GCC的版本12，PaddlePaddle2.4。PadddlePaddle的安装没问题，run_check()检查过。遇到了同样的错误。
