### ISSUE TITLE
mask rtdetr 导出模型 C++部署使用trt加载报错

### ISSUE THREAD

**Issue by yski** [PaddlePaddle/PaddleDetection#9152]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

-windows
-c++
-导出环境：paddle3.0b1/paddledetection develop
-推理环境 paddle inference 3.0.0 beat1 
使用 cpu 加载模型：正常
使用 cuda 加载模型：正常
使用 trt 加载模型报错如下：
![image](https://github.com/user-attachments/assets/8adebbaa-0674-4766-bd51-198e7d14aa73)
![image](https://github.com/user-attachments/assets/fa5db0f1-183f-416a-833c-5fe5842b15f9)

![image](https://github.com/user-attachments/assets/3970c968-a81a-4369-b719-f4661b55e8d9)

'''
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: paddle::get failed, cannot get value (desc.GetAttr("dim")) by type class std::vector<int,class std::allocator<int> >, its type is class std::vector<__int64,class std::allocator<__int64> >. (at C:\home\workspace\Paddle\paddle\fluid\inference\tensorrt\op_teller.cc:2329)
'''

### 复现环境 Environment

-windows
-c++
-导出环境：paddle3.0b1/paddledetection develop
-推理环境 paddle inference 3.0.0 beat1 

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by liu-jiaxuan** [comment]
The error message Conversion to JSON format is not supported indicates that there is an issue with the result type being returned by the model, specifically the SegmentationResult. This suggests that the FastDeploy might not be able to serialize the output in the expected JSON format.
﻿
Ensure that the model you are using is compatible with the FastDeploy framework and TensorRT optimizations. Some models may have layers or operations that are not supported in the current FastDeploy version. Consider using a simpler model or re-evaluating the model architecture.If possible, update to the latest version. 
﻿
Besides,  you can debug the outputs of your model manually to ensure they are in the expected format.

**Comment by liu-jiaxuan** [comment]
Hi，根据您提供的错误信息，存在几个问题：
1. 操作符兼容性：您的模型中的某些操作符在当前trt配置下可能不兼容，请对照文档检查您的模型，确保使用的操作符在trt中支持。
2. 维度错误：出现的 InvalidArgumentError 提示可能是由于输入或输出维度不符合预期，请确认输入数据的维度是否与模型要求一致。
此外，您也可以尝试更新到最新的FastDeploy和trt版本~

**Comment by yski** [comment]
> Hi，根据您提供的错误信息，存在几个问题：
> 
> 1. 操作符兼容性：您的模型中的某些操作符在当前trt配置下可能不兼容，请对照文档检查您的模型，确保使用的操作符在trt中支持。
> 2. 维度错误：出现的 InvalidArgumentError 提示可能是由于输入或输出维度不符合预期，请确认输入数据的维度是否与模型要求一致。
>    此外，您也可以尝试更新到最新的FastDeploy和trt版本~

你好，我这边是使用教程导出的模型，在cuda和cpu模式下可以运行，RT-DETR系列模型trt导出在文档中有提及使用 --trt 参数，Mask-RTDETR导出代码是否忘记处理这部分了？
我这边使用的paddle_inference是这个版本，已经是官网最新的了
https://paddle-inference-lib.bj.bcebos.com/3.0.0-beta1/cxx_c/Windows/GPU/x86-64_cuda12.3_cudnn9.0.0_trt8.6.1.6_mkl_avx_vs2019/paddle_inference.zip

这个文件名对应的cuda12.3_cudnn9.0.0_trt8.6.1.6，
但是里面解压的后编译文件类容版显示是不一样的，我按照下面编译文件配置的cuda cudnn trt
 Paddle version: 3.0.0-beta1
GIT COMMIT ID: a842a0f40f6111fb0c2df218130d0560aa747bc8
WITH_MKL: ON
WITH_ONEDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
WITH_IPU: OFF
CUDA version: 12.0
CUDNN version: v8.9
CXX compiler version: 19.29.30154.0
WITH_TENSORRT: ON
TensorRT version: v8.6.1.6

**Comment by Bobholamovic** [comment]
你好，由于mask rtdetr的部分tensor依赖于输入tensor（scale factor和im_shape）的数值，在使用trt时，可能需要确保在collect shapes时使用的scale_factor和im_shape的数值与真实数据匹配，而不是构造的dummy数据。

**Comment by yski** [comment]
> 你好，由于mask rtdetr的部分tensor依赖于输入tensor（scale factor和im_shape）的数值，在使用trt时，可能需要确保在collect shapes时使用的scale_factor和im_shape的数值与真实数据匹配，而不是构造的dummy数据。
你好，如何修复这个问题呢？或者使用的时候应该怎么操作避免这个问题？能给一段示例代码吗

**Comment by Bobholamovic** [comment]
这个可能涉及到套件具体代码的用法，辛苦 @liu-jiaxuan 看看呢

**Comment by yski** [comment]
> 你好，由于mask rtdetr的部分tensor依赖于输入tensor（scale factor和im_shape）的数值，在使用trt时，可能需要确保在collect shapes时使用的scale_factor和im_shape的数值与真实数据匹配，而不是构造的dummy数据。

大佬上面的代码是没有启用config.EnableTunedTensorRtDynamicShape()

下面是启用后的报错：
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1018 11:21:37.696400 22608 helper.h:131] 4: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::3726] Error Code 4: Internal Error (Could not find any implementation for node {ForeignNode[share_data (Output: detach_gather_nd_0.tmp_0_0_subgraph_1535)...concat (Output: concat_11.tmp_0_subgraph_1677)]} due to insufficient workspace. See verbose log for requested sizes.)
E1018 11:21:37.749327 22608 helper.h:131] 2: [builder.cpp::nvinfer1::builder::Builder::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
![image](https://github.com/user-attachments/assets/83b04f73-6913-4376-ac35-0d2b1f2bc126)

**Comment by liu-jiaxuan** [comment]
Hi，启用后是否保证了 collect shapes 时使用的 scale_factor 和 im_shape 的数值与真实数据匹配呢？无论是否启用nableTunedTensorRtDynamicShape()，均需要保证这一点，目前我们还没有针对这个特定问题的示例代码，可以参考你的数据特点和官方教程调整各参数

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by happeace613** [comment]
> Hi，启用后是否保证了 collect shapes 时使用的 scale_factor 和 im_shape 的数值与真实数据匹配呢？无论是否启用nableTunedTensorRtDynamicShape()，均需要保证这一点，目前我们还没有针对这个特定问题的示例代码，可以参考你的数据特点和官方教程调整各参数

遇到了类似的tensorrt部署问题。collect shape之后，问题如下：
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
collect_trt_shape_info: False
combine_method: nms
cpu_threads: 12
device: gpu
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: dataset/coco/test/
image_file: None
match_metric: ios
match_threshold: 0.6
model_dir: weights/mask_rtdetr/inference/mask_rtdetr_hgnetv2_s_6x_coco
output_dir: output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: trt_fp32
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
task_type: Detection
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
tuned_trt_shape_file: shape_range_info.pbtxt
use_coco_category: False
use_dark: True
use_fd_format: False
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: DETR
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
Use dynamic shape file: shape_range_info.pbtxt for TRT...
I1105 18:07:22.639236  4416 analysis_predictor.cc:1532] TensorRT subgraph engine is enabled
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
I1105 18:07:22.650508  4416 executor.cc:187] Old Executor is Running.
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [trt_remove_amp_strategy_op_pass]e[0m
e[32m--- Running IR pass [trt_support_nhwc_pass]e[0m
e[32m--- Running IR pass [adaptive_pool2d_convert_global_pass]e[0m
e[32m--- Running IR pass [trt_map_ops_to_matrix_multiply_pass]e[0m
I1105 18:07:22.720872  4416 fuse_pass_base.cc:59] ---  detected 119 subgraphs
e[32m--- Running IR pass [shuffle_channel_detect_pass]e[0m
W1105 18:07:22.727331  4416 op_compat_sensible_pass.cc:279] The No optional Output (XShape) of Operator (transpose2) not find in op_desc!
W1105 18:07:22.727331  4416 shuffle_channel_detect_pass.cc:89] The Pass in op compat failed.
W1105 18:07:22.728332  4416 op_compat_sensible_pass.cc:279] The No optional Output (XShape) of Operator (transpose2) not find in op_desc!
W1105 18:07:22.728332  4416 shuffle_channel_detect_pass.cc:89] The Pass in op compat failed.
W1105 18:07:22.728332  4416 op_compat_sensible_pass.cc:279] The No optional Output (XShape) of Operator (transpose2) not find in op_desc!
W1105 18:07:22.728332  4416 shuffle_channel_detect_pass.cc:89] The Pass in op compat failed.
W1105 18:07:22.728332  4416 op_compat_sensible_pass.cc:279] The No optional Output (XShape) of Operator (transpose2) not find in op_desc!
W1105 18:07:22.728332  4416 shuffle_channel_detect_pass.cc:89] The Pass in op compat failed.
W1105 18:07:22.728332  4416 op_compat_sensible_pass.cc:279] The No optional Output (XShape) of Operator (transpose2) not find in op_desc!
W1105 18:07:22.728332  4416 shuffle_channel_detect_pass.cc:89] The Pass in op compat failed.
W1105 18:07:22.728332  4416 op_compat_sensible_pass.cc:279] The No optional Output (XShape) of Operator (transpose2) not find in op_desc!
W1105 18:07:22.728332  4416 shuffle_channel_detect_pass.cc:89] The Pass in op compat failed.
e[32m--- Running IR pass [quant_conv2d_dequant_fuse_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_op_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_filter_op_pass]e[0m
e[32m--- Running IR pass [trt_delete_weight_dequant_linear_op_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_linear_op_pass]e[0m
e[32m--- Running IR pass [identity_op_clean_pass]e[0m
I1105 18:07:22.825580  4416 fuse_pass_base.cc:59] ---  detected 4 subgraphs
e[32m--- Running IR pass [add_support_int8_pass]e[0m
I1105 18:07:24.840785  4416 fuse_pass_base.cc:59] ---  detected 1241 subgraphs
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [trt_prompt_tuning_embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [trt_embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [preln_embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [trt_multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [trt_multihead_matmul_fuse_pass_v3]e[0m
e[32m--- Running IR pass [multihead_matmul_roformer_fuse_pass]e[0m
e[32m--- Running IR pass [constant_folding_pass]e[0m
I1105 18:07:35.578497  4416 fuse_pass_base.cc:59] ---  detected 94 subgraphs
e[32m--- Running IR pass [trt_flash_multihead_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [trt_cross_multihead_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [vit_attention_fuse_pass]e[0m
e[32m--- Running IR pass [trt_qk_multihead_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [layernorm_shift_partition_fuse_pass]e[0m
e[32m--- Running IR pass [merge_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [preln_residual_bias_fuse_pass]e[0m
I1105 18:07:36.220646  4416 fuse_pass_base.cc:59] ---  detected 20 subgraphs
e[32m--- Running IR pass [preln_layernorm_x_fuse_pass]e[0m
e[32m--- Running IR pass [reverse_roll_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I1105 18:07:36.329308  4416 fuse_pass_base.cc:59] ---  detected 59 subgraphs
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
W1105 18:07:36.361337  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.361337  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W1105 18:07:36.362342  4416 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W1105 18:07:36.362342  4416 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
I1105 18:07:36.372341  4416 fuse_pass_base.cc:59] ---  detected 59 subgraphs
e[32m--- Running IR pass [remove_padding_recover_padding_pass]e[0m
e[32m--- Running IR pass [delete_remove_padding_recover_padding_pass]e[0m
e[32m--- Running IR pass [dense_fc_to_sparse_pass]e[0m
e[32m--- Running IR pass [dense_multihead_matmul_to_sparse_pass]e[0m
e[32m--- Running IR pass [tensorrt_subgraph_pass]e[0m
I1105 18:07:36.653998  4416 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 1027 nodes
W1105 18:07:36.665998  4416 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named tile_2.tmp_0 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W1105 18:07:36.666994  4416 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named tile_0.tmp_0 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W1105 18:07:36.666994  4416 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named tmp_176 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W1105 18:07:36.666994  4416 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named tmp_174 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
I1105 18:07:36.850567  4416 tensorrt_subgraph_pass.cc:846] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
W1105 18:07:38.739285  4416 place.cc:161] The `paddle::PlaceType::kCPU/kGPU` is deprecated since version 2.3, and will be removed in version 2.4! Please use `Tensor::is_cpu()/is_gpu()` method to determine the type of place.
W1105 18:07:38.824608  4416 helper.h:127] Tensor DataType is determined at build time for tensors not marked as input or output.
W1105 18:07:38.856666  4416 helper.h:127] Tensor DataType is determined at build time for tensors not marked as input or output.
W1105 18:07:38.891832  4416 helper.h:127] Tensor DataType is determined at build time for tensors not marked as input or output.
W1105 18:07:38.891832  4416 helper.h:127] Tensor DataType is determined at build time for tensors not marked as input or output.
W1105 18:07:38.892833  4416 helper.h:127] Tensor DataType is determined at build time for tensors not marked as input or output.
Traceback (most recent call last):
  File "E:\Detection\deploy\python\infer.py", line 1281, in <module>
    main()
  File "E:\Detection\deploy\python\infer.py", line 1214, in main
    detector = eval(detector_func)(
               ^^^^^^^^^^^^^^^^^^^^
  File "E:\Detection\deploy\python\infer.py", line 110, in __init__
    self.predictor, self.config = load_predictor(
                                  ^^^^^^^^^^^^^^^
  File "E:\Detection\deploy\python\infer.py", line 1113, in load_predictor
    predictor = create_predictor(config)
                ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: (InvalidArgument) paddle::get failed, cannot get value (op_desc.GetAttr("dim")) by type class std::vector<int,class std::allocator<int> >, its type is class std::vector<__int64,class std::allocator<__int64> >. (at ..\paddle\fluid\inference\tensorrt\convert\reduce_op.cc:152)
测试环境：
win11，python 3.11，paddledetection 2.8.1, paddle 2.6.2, cuda 11.7, tensorrt 8.4/8.5, cudnn8.4(官方链接： pip安装方式 pip install paddlepaddle-gpu==2.6.2.post117 -i https://www.paddlepaddle.org.cn/packages/stable/cu117/
 以及conda安装方式 conda install paddlepaddle-gpu==2.6.2 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge )
报错的像是维度数据类型问题，需要int类型，实际传入的却是int64。像是paddle 2.6.2/2.6.1/2.6.0的bug？请官方看看倒是哪儿的问题？
